Intentions ::= (User Ordering) | Auto ( Invoicing | Delivering | Confirming ) "."

Auto ::= 'We are '

Delivering ::= (Paying | Cashing) Delivery Signature

Paying ::= 'paying ' Cash ' in order for ' Asset

Cashing ::= 'cashing ' Asset ' in order for ' Cash

Delivery ::= ' and delivery is good until the market volume reaches ' ExactAmount

Signature ::= ' using the signature ' AlphaNumeric

Asset ::= ExactAmount ' using ' AssetAddress

Cash ::= ExactAmount ' using ' CashAddress

ExactAmount ::= ' exactly ' Numeric Units

AssetAddress ::= ' the ' AssetUnits ' address ' AlphaNumeric

CashAddress ::= ' the SWOBL address ' AlphaNumeric

AssetUnits ::= 'BTC' | 'ETH'
